### ISSUE TITLE
Validate any Hash

### ISSUE THREAD

**Issue by andresespinosapc** [DmitryTsepelev/store_model#114]
Is it possible to use a StoreModel to validate any Hash or json, without it being in a model?

My use case is that I have an API that returns a list of shipment methods, the user selects one of them and then a request is made to create a record with that shipment method as a jsonb column. I want to validate that the structure is right in the API that returns the shipment methods in the first place.

**Comment by DmitryTsepelev** [comment]
Hi @andresespinosapc! `store_model` uses built–in ActiveRecord validation mechanisms, which happen before saving record to the database. Since you don't want to save your JSON and only validate it you might want to consider a different approach: you can describe the schema you expect and check if a given JSON is valid using https://github.com/voxpupuli/json-schema
