### ISSUE TITLE
Saving Unknown Attributes

### ISSUE THREAD

**Issue by ishields** [DmitryTsepelev/store_model#56]
Is it possible to have store_model to store unknown attributes?  The .unknown_attributes method is extremely useful however upon saving the record the unknown attributes are lost.  It would be useful to save these attributes so they can later be added to the model and their value would then be accessible.

**Comment by DmitryTsepelev** [comment]
Hi @ishields! Unfortunately, it's not possible right now, because no one asked for it before 🙂 If I'm not mistaken, the method was introduced to handle the situation when there is a legacy column with extra data you don't care, but don't want serialiser to crash.

It feels like the implementation is going to be fairly simple: when unknown attributes are found we [store](https://github.com/DmitryTsepelev/store_model/blob/5e59d867a9333746a17b0b0bacbc7944fae7525d/lib/store_model/types/json_type.rb#L88) them to the `unknown_attributes` hash, in order to avoid erasing them we just need to change [this](https://github.com/DmitryTsepelev/store_model/blob/5e59d867a9333746a17b0b0bacbc7944fae7525d/lib/store_model/model.rb#L27) line (to something line `attributes.with_indifferent_access.merge(unknown_attributes).as_json(options)`). Do you want to try it out? 🙂

**Comment by ishields** [comment]
Yea I can take a look! One thing that would be nice with this is if you then add the attribute that was unknown it translates it into it. And the other way around - if a model attribute is removed.

**Comment by DmitryTsepelev** [comment]
You mean you want to be able to _add_ and unknown attribute to the model and have it saved? Something like:

```ruby
class Configuration
  include StoreModel::Model

  attribute :model, :string
end

configuration = Configuration.new
configuration.model = "XR"
configuration.unknown.color = "red"
```
